# Generated by Django 4.1.4 on 2023-01-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_alter_amenity_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="kind",
            field=models.CharField(
                choices=[
                    ("entire_place", "Entire Place"),
                    ("private_room", "Private Room"),
                    ("shared_room", "Shared Room"),
                ],
                max_length=20,
            ),
        ),
    ]
