# Generated by Django 4.1.4 on 2023-01-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_room_cateogry_alter_room_amenities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="cateogry",
            new_name="category",
        ),
    ]
