# Generated by Django 4.1.4 on 2023-02-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0002_alter_photo_file_alter_video_file"),
        ("rooms", "0008_rename_cateogry_room_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="photos",
            field=models.ManyToManyField(related_name="rooms", to="medias.photo"),
        ),
    ]
