# Generated by Django 4.1.4 on 2023-01-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('price_per_night', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('address', models.TextField(max_length=140)),
                ('pet_allowed', models.BooleanField(default=True, help_text='mong mong!')),
            ],
        ),
    ]
